### ISSUE TITLE
Your Unsplash API key is showing

### ISSUE THREAD

**Issue by DavidR-sevenbel** [cmota/a-composable-new-world#4]
@cmota you published your Unsplash API key in the following files:
- [UnsplashAPI.kt in 00.Starter Project](https://github.com/cmota/a-composable-new-world/blob/main/00.Starter%20Project/app/src/main/java/com/cmota/unsplash/shared/data/UnsplashAPI.kt)
- [UnsplashAPI.kt in 01.Creating Your First Screen](https://github.com/cmota/a-composable-new-world/blob/main/01.Creating%20Your%20First%20Screen/app/src/main/java/com/cmota/unsplash/shared/data/UnsplashAPI.kt)
- [UnsplashAPI.kt in 02.Creating Your Second Screen](https://github.com/cmota/a-composable-new-world/blob/main/02.Creating%20Your%20Second%20Screen/app/src/main/java/com/cmota/unsplash/shared/data/UnsplashAPI.kt)
- [UnsplashAPI.kt in 03.Theming and Styling](https://github.com/cmota/a-composable-new-world/blob/main/03.Theming%20and%20Styling/app/src/main/java/com/cmota/unsplash/shared/data/UnsplashAPI.kt)
- [UnsplashAPI.kt in 04.Navigating Between Screens](https://github.com/cmota/a-composable-new-world/blob/main/04.Navigating%20Between%20Screens/app/src/main/java/com/cmota/unsplash/shared/data/UnsplashAPI.kt)
- [UnsplashAPI.kt in 05.Managing State](https://github.com/cmota/a-composable-new-world/blob/main/05.Managing%20State/app/src/main/java/com/cmota/unsplash/shared/data/UnsplashAPI.kt)

I suggest revoking the key with Unsplash :)

**Comment by cmota** [comment]
I've added it initially because it was a live workshop and I wanted to people easily checkout the project. But you're right; removed it. Thank you for the heads up 🙂.
